---
- name: Check for config_inc.php
  stat:
    path: "{{ mantis_dir }}/config_inc.php"
  register: mantis_config_inc_file

- name: Copy config_inc.php
  sudo: yes
  template:
    src: config_inc.php.j2
    dest: "{{ mantis_dir }}/config_inc.php"
    mode: 0755
    owner: root
    group: root
  when: mantis_config_inc_file.stat.exists == false

- name: Remove admin directory.
  file:
    path: "{{ mantis_dir }}/admin"
    state: absent
